process assign {
    publishDir "${params.output}/${name}/${params.taxdir}", mode: 'copy', pattern: "*_taxonomy.tsv"
    publishDir "${params.output}/${name}/${params.finaldir}/taxonomy", mode: 'copy', pattern: "*_taxonomy.tsv"
    label 'assign'

    input:
      tuple val(name), val(set_name), file(tab)
      file(db)
      file(factor)
    
    output:
      tuple val(name), val(set_name), file("*_taxonomy.tsv")
    
    script:
    """
    contig_taxonomic_assign.py -i ${tab} -d ${db} --factor ${factor} --taxthres ${params.taxthres}
    """
}

/*
	'''This function takes the annotation table generated by viral_contig_maps.py and generates a table that
	   provides the taxonomic lineage of each viral contig, based on the corresponding ViPhOG annotations'''

*/