language: python
python: 3.8

services:
  - docker

install:
  - pip install -r cwl/requirements/pip_test_requirements.txt

script:
  # CWL validation
  # TODO, this is failing for some reason
  # - cwltool --validate $TRAVIS_BUILD_DIR/cwl/src/pipeline.cwl
  # CWL tests
  - cd $TRAVIS_BUILD_DIR/cwl/tests
  # NOTE: run only tests that do not require DBs or files from the FTP server
  - bash cwltest.sh --test tests.yml -j 4 --verbose -n 1,4,5,6,10,11,12,13,14,20
  # python tests
  - cd $TRAVIS_BUILD_DIR/
  - python -m unittest discover tests

cache: pip