process ASSIGN {
/*
	'''This function takes the annotation table generated by viral_contig_maps.py and generates a table that
	   provides the taxonomic lineage of each viral contig, based on the corresponding ViPhOG annotations'''

*/
    tag "${meta.id} ${set_name}"
    label 'process_single'
    
    container 'quay.io/microbiome-informatics/virify-python3:1.1'
    
    input:
      tuple val(meta), val(set_name), path(tab)
      path(db)
      path(factor)
    
    output:
      tuple val(meta), val(set_name), path("*_taxonomy.tsv")
    
    script:
    def version4 = params.meta_version == 'v4' ? '--version4' : ''
    """
    contig_taxonomic_assign.py ${version4} -i ${tab} -d ${db} --factor ${factor} --taxthres ${params.taxthres} 
    """
}