process ASSIGN {
/*
	'''This function takes the annotation table generated by viral_contig_maps.py and generates a table that
	   provides the taxonomic lineage of each viral contig, based on the corresponding ViPhOG annotations'''

*/
    tag "${name}"
    label 'process_low'
    
    container 'quay.io/microbiome-informatics/virify-python3:1.1'
    
    input:
      tuple val(name), val(set_name), file(tab)
      file(db)
      file(factor)
    
    output:
      tuple val(name), val(set_name), file("*_taxonomy.tsv")
    
    script:
    """
    contig_taxonomic_assign.py -i ${tab} -d ${db} --factor ${factor} --taxthres ${params.taxthres}
    """
}