FROM perl:latest

MAINTAINER Ken Youens-Clark <kyclark@email.arizona.edu>

COPY Generic_ref_file.refs /data/

COPY PFAM_27 /data/PFAM_27

COPY Phage_gene_catalog /data/Phage_gene_catalog

COPY Phage_gene_catalog_plus_viromes /data/Phage_gene_catalog_plus_viromes

COPY SUP05_SAGs_with_viruses.fna /data/

COPY VirSorter_Readme.txt /data/

COPY VirSorter_Readme_viromes.txt /data/

VOLUME ["/data"]
