process assign {
      publishDir "${params.output}/${name}/${params.taxdir}", mode: 'copy', pattern: "${set_name}_prodigal_prot_ann_table_tax_assign.tsv"
      publishDir "${params.output}/${name}/${params.finaldir}/taxonomy", mode: 'copy', pattern: "${set_name}_prodigal_prot_ann_table_tax_assign.tsv"
      label 'assign'

    input:
      tuple val(name), val(set_name), file(tab)
      file(db)
    
    output:
      tuple val(name), val(set_name), file("${set_name}_prodigal_prot_ann_table_tax_assign.tsv")
    
    script:
    """
    contig_taxonomic_assign.py -i ${tab} -d ${db} --prop ${params.prop} --taxthres ${params.taxthres}
    cp *tax_assign.tsv tmp && rm *tax_assign.tsv && cp tmp ${set_name}_prodigal_prot_ann_table_tax_assign.tsv
    """
}

/*
	'''This function takes the annotation table generated by viral_contig_maps.py and generates a table that
	   provides the taxonomic lineage of each viral contig, based on the corresponding ViPhOG annotations'''

*/