name: viral_pipeline
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast=2.9.0
  - hmmer=3.1b2
  - krona=2.7.1
  - mashmap=2.0
  - prodigal=2.6.3
  - virsorter=1.0.6  
  - r-virfinder=1.1
  - python=3.7.3
  - pip=20.1.1
  - perl-bioperl-core=1.007002
  - r-purrr=0.3.2
  - pip:
    - biopython==1.74
    - cwltest==2.0.20200220223835
    - cwltool==3.0.20200324120055
    - ete3==3.1.1
    - flake8==3.8.2
    - html5lib==1.0.1
    - numpy==1.17.0
    - pandas==0.25.3
    - pyflakes==2.2.0
    - pyyaml==5.3
    - rdflib==4.2.2
    - toil[cwl]==5.3.0
    - boto==2.49.0
    - boto3==1.17.57
    - schema-salad==5.0.20200416112825
