name: Linting

on:
  push:
    branches: [ "master", "fix/github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: |
            3.11
            3.12
            3.13
        cache: "pip"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-test.txt pre-commit

    - name: Run the precommits
      run: pre-commit run -a
